version: '3'
services:
  #授权服务
  mogu_spider:
    image: registry.cn-shenzhen.aliyuncs.com/mogublog/mogu_spider:latest
    container_name: mogu_spider
    restart: always
    ports:
      - 8608:8608
    networks:
      - mogu
    environment:
      - COMPOSE_PROJECT_NAME=mogu_spider
    volumes:
      - ../log/:/logs/
networks:
  mogu:
    external: true